name: GitHub Metrics
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  github-metrics:
    runs-on: ubuntu-26.04
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: output/general-metrics.svg
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_display: large
          config_order: base.header, isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

